add-shoppingCart-model
VolodymyrDavidov/BookHaven pull request #13
Opened 2023-12-08 10:51 UTC by VolodymyrDavidov

2023-12-08 13:25 UTC, VolodymyrDavidov commented
Sorry, forgot about command git stash apply

2023-12-08 16:39 UTC, okuzan requested changes

2023-12-08 16:39 UTC, okuzan commented on src/main/java/com/project/bookhaven/service/shoppingcart/ShoppingCartServiceImpl.java
> +    }
huge chunk of code is hard to read, consider breaking it into smaller private methods with descriptive names

2023-12-09 16:43 UTC, olekskov approved these changes

2023-12-09 18:31 UTC, merged